title: "Sun Lab"
description: "High-throughput structural proteomics • Mass spectrometry • AI for biology"
theme: jekyll-theme-cayman

# 你的 GitHub Pages 域名（不要带仓库名）
url: "https://suninuniverse.github.io"
# 你的仓库名（必须以 / 开头）
baseurl: "/sun-lab"

# 顶部导航栏（首页 index.md 不需要放进来）
header_pages:
  - research.md
  - people.md
  - instruments.md
  - publications.md
  - lab-info.md
  - join-us.md

markdown: kramdown
kramdown:
  input: GFM
