title: "Sun Lab"
description: "High-throughput structural proteomics • Mass spectrometry • AI for biology"
theme: jekyll-theme-cayman

url: "https://suninuniverse.github.io"
baseurl: "/sun-lab"

header_pages:
  - research.md
  - publications.md
  - people.md
  - instruments.md
  - lab-info.md
  - join-us.md

markdown: kramdown
kramdown:
  input: GFM
